### PR TITLE
update Schema with a File model and add corresponding relations for photos 

### PR DESCRIPTION
**Pull request by nancychuchu**
update Schema with a File model and add corresponding relations for photos

### CODE REVIEW

**Review by teelau — CHANGES_REQUESTED** [review]
Fix conflicts, rebase on develop

**Review by siddharthparmar7 — APPROVED** [review]

**Review by siddharthparmar7 — CHANGES_REQUESTED** [review]
Please resolve merge conflicts.

**Comment by siddharthparmar7** [comment]
Please connect this pull request with an issue and resolve merge conflicts. Thank you.

**Comment by nancychuchu** [comment]
Fixed merge conflicts and connected pull request to issue

**Review by teelau — DISMISSED** [review]

**Review by siddharthparmar7 — APPROVED** [review]

**Pull request merged**
